#!/bin/bash

# author: Fabian Ostermann
# 2020/29/01

## MAKE ASG Library ##
cd ASGLib/
#./?

## MAKE ArtificialSongGenerator ##
cd ../ArtificialSongGenerator/
./makejar

## MAKE OnsetAnnotator ##
cd ../OnsetAnnotator/
./makejar

cd ../SamplingRoboter/
./makejar

