#!/bin/bash

# author: Fabian Ostermann
# 2019/02/28

### global variables ###

# executables
ArtificialSongGenerator_JAR=../ArtificialSongGenerator/ArtificialSongGenerator.jar

DIR="." # if empty directory string, files will be stored on path directory


### handle options ###

# handle help option
if [ "$1" == "-h" -o "$1" == "--help" ]; then
  echo "This scripts generates a bunch of random midi songs using the ArtificialSongGenerator"
  echo "Java-Runtime-Env must be installed on the System."
  echo ""
  echo "ALL Parameters are used as file IDs."
  echo "Example: ./generate-songs File1 File2"
  echo "     or: ./generate-songs {001..100}"
  echo ""
  echo "Use '--dir' to specify a directory for all files to go (will be created)"
  echo "Example: ./generate-songs --dir <directory> File1"
  echo ""
  echo "Use '--config' to specify a specific config file to be used (default is 'thesong.conf')"
  echo "Example: ./generate-songs --config <configfile> File1"
  echo ""
  # help aborts program
  exit 0
fi

if [ ! -f $ArtificialSongGenerator_JAR ]; then
  echo "Jar file $ArtificialSongGenerator_JAR not found."
  exit 1
fi

# handle directory option
if [ "$1" == "--dir" ]; then
  DIR="$2"
  shift $((OPTIND+1)) # consume option and argument
fi

if [ "$DIR" == "." ]; then
  echo "Empty directory string, using script's directory."
else
  # create directory if needed
  echo "create directory: $DIR"
  mkdir -p "$DIR"
fi

if [ "$1" == "--config" ]; then
  CONFIG_COMMAND="--config=$2"
  shift $((OPTIND+1)) # consume option and argument
fi

### do actual calculations ###

for ID in $@; do
  ## info
  echo "=== $ID ==="
  # generate midis and annotations
  java -jar $ArtificialSongGenerator_JAR --title=$ID --dir=$DIR $CONFIG_COMMAND
done





