#!/bin/bash

# compile java given the jfugue library and source and binary directory
mkdir -p ./bin
echo "compiling OnsetAnnotator to ./bin/"
javac -source 1.8 -target 1.8 -d ./bin/ ./src/*/*.java ../ASGLib/src/*/*.java

