#!/bin/bash

# author: Fabian Ostermann
# 2019/02/28

MANIFEST_FILE="manifest.mf"

echo "NOTE: experimental script (using eclipse is safer)"

## MAKE OnsetAnnotator ##
./compile

# META-INF/MANIFEST.MF:
touch $MANIFEST_FILE
echo "Manifest-Version: 1.0" > $MANIFEST_FILE
#echo "Rsrc-Class-Path: ." >> $MANIFEST_FILE
echo "Class-Path: ." >> $MANIFEST_FILE
echo "Main-Class: OnsetAnnotator" >> $MANIFEST_FILE

jar cfm OnsetAnnotator.jar $MANIFEST_FILE -C ./bin/ .

rm $MANIFEST_FILE

echo -n "created: "
ls OnsetAnnotator.jar
