#!/bin/sh

filename=ASGLib/src/info/Version.java
version="0.1" # manuell
datestr=`date +"%Y/%m/%d-%H:%M"` # automatic hooked

versionstr="v$version-$datestr"

echo "post-commit: set version to $versionstr"

oldfilecontent=`cat $filename`
newfilecontent=`echo "package info; public class Version { public static final String VERSION = \"$versionstr\"; }"`

echo -e "old version file content:\n$oldfilecontent"
echo -e "new version file content:\n$newfilecontent"

if [ "$oldfilecontent" = "$newfilecontent" ]
  then
    echo "post-commit: done."
  else
	echo $newfilecontent > $filename
    git add $filename
    git commit --amend -C HEAD --no-verify
    echo "version file updated"
fi

exit 0
