#!/bin/sh

version="0.2" # manuell
# recently removed "-%H:%M" from version statement
datestr=`date +"%Y/%m/%d"` # automatic hooked 
filename=ASGLib/src/info/Version.java

versionstr="v$version-$datestr"

echo "post-commit: set version to $versionstr"

oldfilecontent=`cat $filename`
newfilecontent=`echo "package info; public class Version { public static final String VERSION = \"$versionstr\"; }"`

if [ "$oldfilecontent" = "$newfilecontent" ]
  then
    echo "post-commit: done."
  else
    echo -e "old version file content:\n$oldfilecontent"
    echo -e "new version file content:\n$newfilecontent"		
    echo $newfilecontent > $filename
    git add $filename
    git commit --amend -C HEAD --no-verify
    echo "version file updated"
fi

exit 0
