#!/bin/bash

if [ ! -f ./lib/jfugue-5.0.9.jar ];then
  wget -P ./lib/ www.jfugue.org/jfugue-5.0.9.jar
else
  echo "found jfugue-5.0.9 installation"
fi

# compile java given the jfugue library and source and binary directory
mkdir -p ./bin
echo "compiling ArtificialSongGenerator to ./bin/"
javac -s ./src/ -d ./bin/ -cp ./lib/jfugue-5.0.9.jar ./src/*/*.java

